name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug SSH Connection
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          echo "Checking EC2 connectivity..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} "echo Connected to EC2 successfully!"

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Stopping existing app..."
            docker stop go-app || true
            docker rm go-app || true
            echo "Pulling latest image..."
            docker pull navaneetha084/go-app:latest
            echo "Starting new container on port 8000..."
            docker run -d --name go-app -p 8000:8000 navaneetha084/go-app:latest
            echo "Deployment successful!"
