name: Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go-app:latest
            
            # Stop and remove the old container if it exists
            docker stop go-app || true
            docker rm go-app || true
            
            # Run the new container
            docker run -d --name go-app -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/go-app:latest
            
            # Wait for the app to start
            sleep 5
            
            # Check if the app is running
            if curl -s http://${{ secrets.EC2_IP }}:8000; then
              echo "✅ Application is running successfully!"
            else
              echo "❌ Failed to start application."
              exit 1
            fi

      - name: Display App URL
        run: |
          echo "Your Go App is deployed successfully!"
          echo "Click to open: http://${{ secrets.EC2_IP }}:8000"

