name: Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    needs: [ci_cd, trivy-scan]  # Ensure deploy happens after build & scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
          echo "Connecting to EC2 and deploying..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go-app:latest

            echo "Stopping old container..."
            docker stop go-app || true
            docker rm go-app || true

            echo "Running new container..."
            docker run -d -p 8000:8000 --name go-app ${{ secrets.DOCKERHUB_USERNAME }}/go-app:latest
          EOF

      - name: Display Deployed URL
        run: |
          echo "🚀 Your Go App is deployed successfully!"
          echo "🔗 Click to open: http://${{ secrets.EC2_HOST }}:8000"
